// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AboutShow() {
  return window['go']['application']['App']['AboutShow']();
}

export function AppSettingCreate() {
  return window['go']['application']['App']['AppSettingCreate']();
}

export function AppSettingDelete(arg1) {
  return window['go']['application']['App']['AppSettingDelete'](arg1);
}

export function AppSettingEdit(arg1) {
  return window['go']['application']['App']['AppSettingEdit'](arg1);
}

export function AppSettingList() {
  return window['go']['application']['App']['AppSettingList']();
}

export function AppSettingSave(arg1) {
  return window['go']['application']['App']['AppSettingSave'](arg1);
}

export function DashboardShow() {
  return window['go']['application']['App']['DashboardShow']();
}

export function InternalSettingList() {
  return window['go']['application']['App']['InternalSettingList']();
}

export function JobShowFiles() {
  return window['go']['application']['App']['JobShowFiles']();
}

export function OpenExternal(arg1) {
  return window['go']['application']['App']['OpenExternal'](arg1);
}

export function RemoteRepositoryCreate() {
  return window['go']['application']['App']['RemoteRepositoryCreate']();
}

export function RemoteRepositoryDelete(arg1) {
  return window['go']['application']['App']['RemoteRepositoryDelete'](arg1);
}

export function RemoteRepositoryEdit(arg1) {
  return window['go']['application']['App']['RemoteRepositoryEdit'](arg1);
}

export function RemoteRepositoryList() {
  return window['go']['application']['App']['RemoteRepositoryList']();
}

export function RemoteRepositorySave(arg1) {
  return window['go']['application']['App']['RemoteRepositorySave'](arg1);
}
