// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {common} from '../models';

export function AboutShow():Promise<application.Response>;

export function AppSettingCreate():Promise<application.Response>;

export function AppSettingDelete(arg1:string):Promise<application.Response>;

export function AppSettingEdit(arg1:string):Promise<application.Response>;

export function AppSettingList():Promise<application.Response>;

export function AppSettingSave(arg1:common.AppSetting):Promise<application.Response>;

export function DashboardShow():Promise<application.Response>;

export function InternalSettingList():Promise<application.Response>;

export function JobShowFiles():Promise<application.Response>;

export function OpenExternal(arg1:string):Promise<application.Response>;
