// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function Debug(arg1:string,arg2:Array<any>):Promise<void>;

export function Error(arg1:string,arg2:Array<any>):Promise<void>;

export function Fatal(arg1:string,arg2:Array<any>):Promise<void>;

export function Info(arg1:string,arg2:Array<any>):Promise<void>;

export function Panic(arg1:any):Promise<void>;

export function SetLogLevel(arg1:common.LogLevel):Promise<void>;

export function Trace(arg1:string,arg2:Array<any>):Promise<void>;

export function Warn(arg1:string,arg2:Array<any>):Promise<void>;
