// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1, arg2) {
  return window['go']['common']['Logger']['Debug'](arg1, arg2);
}

export function Error(arg1, arg2) {
  return window['go']['common']['Logger']['Error'](arg1, arg2);
}

export function Fatal(arg1, arg2) {
  return window['go']['common']['Logger']['Fatal'](arg1, arg2);
}

export function Info(arg1, arg2) {
  return window['go']['common']['Logger']['Info'](arg1, arg2);
}

export function Panic(arg1) {
  return window['go']['common']['Logger']['Panic'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['common']['Logger']['SetLogLevel'](arg1);
}

export function Trace(arg1, arg2) {
  return window['go']['common']['Logger']['Trace'](arg1, arg2);
}

export function Warn(arg1, arg2) {
  return window['go']['common']['Logger']['Warn'](arg1, arg2);
}
