// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DashboardShow() {
  return window['go']['main']['App']['DashboardShow']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RenderNav(arg1) {
  return window['go']['main']['App']['RenderNav'](arg1);
}
