// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppSettingCreate() {
  return window['go']['main']['App']['AppSettingCreate']();
}

export function AppSettingDelete(arg1) {
  return window['go']['main']['App']['AppSettingDelete'](arg1);
}

export function AppSettingEdit(arg1) {
  return window['go']['main']['App']['AppSettingEdit'](arg1);
}

export function AppSettingList() {
  return window['go']['main']['App']['AppSettingList']();
}

export function AppSettingSave(arg1) {
  return window['go']['main']['App']['AppSettingSave'](arg1);
}

export function DashboardShow() {
  return window['go']['main']['App']['DashboardShow']();
}

export function JobShowFiles() {
  return window['go']['main']['App']['JobShowFiles']();
}
