// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AboutShow():Promise<main.Response>;

export function AppSettingCreate():Promise<main.Response>;

export function AppSettingDelete(arg1:string):Promise<main.Response>;

export function AppSettingEdit(arg1:string):Promise<main.Response>;

export function AppSettingList():Promise<main.Response>;

export function AppSettingSave(arg1:string):Promise<main.Response>;

export function DashboardShow():Promise<main.Response>;

export function JobShowFiles():Promise<main.Response>;

export function Log(arg1:string):Promise<void>;
