// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DashboardShow():Promise<main.Response>;

export function JobShowFiles():Promise<main.Response>;
