// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppSettingEdit() {
  return window['go']['main']['App']['AppSettingEdit']();
}

export function AppSettingList() {
  return window['go']['main']['App']['AppSettingList']();
}

export function AppSettingSave() {
  return window['go']['main']['App']['AppSettingSave']();
}

export function DashboardShow() {
  return window['go']['main']['App']['DashboardShow']();
}

export function JobShowFiles() {
  return window['go']['main']['App']['JobShowFiles']();
}
